### ISSUE TITLE
Order sstatus & Payment status showed as All when came back to dashboard after placing order.

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-shit-app#2]
After placing the order when came back to dashboard to the see the order.it showed the order status as all. It should be placed or confirmed. Payment status had also shown all.

**Comment by manoj-mili** [comment]
@Vaishu5 I don't think it is a bug it is implemented that way please let me know why it should show only Placed

**Comment by Vaishu5** [comment]
yes, it should show "Placed". but it was not showing "Placed". Instead of "placed" it was showing "ALL". its working in the current build.
